### ISSUE TITLE
Unable to import .svg generated by boxes.py

### ISSUE THREAD

**Issue by kilpatrq** [CommonWealthRobotics/CaDoodle-Application#16]
I am unable to import the attached .svg file. Upon importing, the icon comes up, displays "addobject running" briefly before disappearing, and then the object is not imported. This .svg is the default box straight from boxes.py, but i also experienced the same issue with a copy of the file that was altered slightly and then saved with inkscape. I am running windows 11 x64.

![ABox](https://github.com/user-attachments/assets/7edc9b2f-069a-4f05-9051-0c462c8e29b6)

**Comment by madhephaestus** [comment]
Whe you look closely at the inner corners of the small rectangle holes you see that the polygon overlaps itself. You can correct this by segmenting out the holes and running "Union" in Inkscape, or by telling boxes.py not to make the corners overlap. I have also modified the cad kernel to fail graacefully when a bad polygon is loaded: https://github.com/NeuronRobotics/JCSG/commit/91b00e46a0fe493610de71c4b11581e0c9cc32b8
