### ISSUE TITLE
Auto-loading last file can be problematic

### ISSUE THREAD

**Issue by JansenSmith** [CommonWealthRobotics/CaDoodle-Application#21]
When working with large files, the current behavior of auto-loading the last used file can result in a slog where a new file cannot be loaded until the wrong file completely loads.

Recommended action: load no file and let the user select a file to load or start with a randomly generated filename that does not auto-save until the user modifies something.

**Comment by madhephaestus** [comment]
start a new doodle, this is intrensic to the file format
